homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 41.9068
  longitude: -87.6718
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 181.3
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: eric
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

logger:
  default: info
  logs:
    homeassistant.components.sensor.hello_sense: debug

# Track the sun
sun:

sensor:
  - platform: hello_sense
    api_key: !secret sense_api_key
  # Weather Prediction
  - platform: wunderground
    api_key: !secret wunderground_api_key
    monitored_conditions:
      - alerts
      - dewpoint_f
      - dewpoint_string
      - feelslike_f
      - feelslike_string
      - heat_index_f
      - heat_index_string
      - elevation
      - location
      - observation_time
      - precip_1hr_in
      - precip_1hr_string
      - precip_today_in
      - precip_today_string
      - pressure_in
      - pressure_trend
      - relative_humidity
      - station_id
      - solarradiation
      - temperature_string
      - temp_f
      - UV
      - visibility_mi
      - weather
      - wind_degrees
      - wind_dir
      - wind_gust_mph
      - wind_mph
      - wind_string


# Text to speech
tts:
  platform: google

