homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include misc/customize.yaml

updater:
discovery:
logbook:
history:
recorder:
  db_url: postgresql:///homeassistant

logger: !include misc/logger.yaml

frontend:
http:
  api_password: !secret http_password

config:
group: !include groups.yaml

emulated_hue:
  type: alexa
  expose_by_default: false

conversation:
tts:
  platform: google

ifttt:
  key: !secret ifttt_key
sun:

light:
  platform: hue
  allow_in_emulated_hue: false
  host: 192.168.1.167

mqtt: !include misc/mqtt.yaml
device_tracker: !include_dir_list device_tracker
switch: !include_dir_list switch
sensor: !include_dir_list sensor
binary_sensor: !include_dir_list binary_sensor
notify: !include_dir_list notify
media_player: !include_dir_list media_player
shell_command: !include misc/shell_commands.yaml

