homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago

updater:
discovery:
logbook:
history:
recorder:
  db_url: postgresql:///homeassistant

logger: !include misc/logger.yaml

frontend:
http:
  api_password: !secret http_password

conversation:
tts:
  platform: google

ifttt:
  key: !secret ifttt_key
sun:
light:
  platform: hue

mqtt: !include misc/mqtt.yaml
device_tracker: !include_dir_list device_tracker
switch: !include_dir_list switch
sensor: !include_dir_list sensor
notify: !include_dir_list notify
shell_command: !include misc/shell_commands.yaml

