substitutions:
  name: bt-proxy
  board: esp32thing

esphome:
  name: ${name}
  name_add_mac_suffix: true

esp32:
  board: ${board}
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "vX+BT9w0rus2+i9Uz/hBiGov5RqdSjK4DNJ39JC5U7Q="

ota:
  password: "4a5be15d33fc9bf43b92298e1361be11"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
