esphome:
  name: "family-room-lamp"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "A1Yt8VqvlazcmaLZut4Wg0LnMnbTyVOs1XnctMb4laQ="

ota:
  password: "511ac7abccab2c745060c9267c5375f1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Device Specific Config
substitutions:
  upper_devicename: "family-room-lamp"
<<: !include sonoff.yaml
