substitutions:
  device_name: RDWC

esphome:
  name: rdwc

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Ie6IuVUD0CLlL4jyidbdtl+sosR1+Dcc2bAZCtyBGuY="

web_server:

button:
  - platform: template
    name: ${device_name} pH Calibration Read
    id: ph_cal_read
    on_press:
      lambda: |-
          id(ph_ezo).get_calibration();
  - platform: template
    name: ${device_name} pH Calibration Mid
    id: ph_cal_mid
    on_press:
      lambda: |-
          id(ph_ezo).send_custom("cal,mid,7.00");
  - platform: template
    name: ${device_name} pH Calibration Low
    id: ph_cal_low
    on_press:
      lambda: |-
          id(ph_ezo).send_custom("cal,low,4.00");
  - platform: template
    name: ${device_name} pH Calibration High
    id: ph_cal_high
    on_press:
      lambda: |-
          id(ph_ezo).send_custom("cal,high,10.00");
  - platform: template
    name: ${device_name} pH Calibration Clear
    id: ph_cal_clear
    on_press:
      lambda: |-
          id(ph_ezo).clear_calibration();

  - platform: template
    name: ${device_name} EC Calibration Read
    id: ec_cal_read
    on_press:
      lambda: |-
          id(ec_ezo).get_calibration();
  - platform: template
    name: ${device_name} EC Calibration Dry
    id: ec_cal_dry
    on_press:
      lambda: |-
          id(ec_ezo).send_custom("cal,dry");
  - platform: template
    name: ${device_name} EC Calibration Low
    id: ec_cal_low
    on_press:
      lambda: |-
          id(ec_ezo).send_custom("cal,low,12880");
  - platform: template
    name: ${device_name} EC Calibration High
    id: ec_cal_high
    on_press:
      lambda: |-
          id(ec_ezo).send_custom("cal,high,80000");
  - platform: template
    name: ${device_name} EC Calibration Clear
    id: ec_cal_clear
    on_press:
      lambda: |-
          id(ec_ezo).clear_calibration();

ota:
  password: "6173e130e66150a96e058f4e2818e100"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rdwc Fallback Hotspot"
    password: "DDmq9Xo9K6OH"

captive_portal:

i2c:
  sda: 4
  scl: 5
  scan: True
  id: bus_a

sensor:
  - platform: ezo
    name: "${device_name} pH"
    id: ph_ezo
    address: 99
    unit_of_measurement: "pH"
    update_interval: 10s
    accuracy_decimals: 2

  - platform: ezo
    id: rtd_ezo
    name: "${device_name} Temperature"
    address: 102
    accuracy_decimals: 2
    unit_of_measurement: "°C"
    update_interval: 10s
    on_value:
      then:
        - lambda: |-
            id(ph_ezo).set_tempcomp_value(id(rtd_ezo).state);
            id(ec_ezo).set_tempcomp_value(id(rtd_ezo).state);
  - platform: ezo
    id: ec_ezo
    name: "${device_name} EC"
    address: 100
    accuracy_decimals: 0
    unit_of_measurement: "EC"
    update_interval: 10s

switch:
  - platform: gpio
    pin: 14
    id: ph_on
    inverted: no

  - platform: gpio
    pin: 15
    id: rtd_temp_on
    inverted: yes

  - platform: gpio
    pin: 12
    id: ppm_on
    inverted: no
