esphome:
  name: "sofa-lights"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Rp3G5Ut6o/wjwJR7MPSIGrP5RGz4OcsPciLJKehTsSs="

ota:
  password: "c49de64eb7184e3072ebee47aed305bb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
# Device Specific Config
substitutions:
  upper_devicename: "Sofa Lights"

<<: !include sonoff.yaml
