uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${upper_devicename} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${upper_devicename} Status"

sensor:
  - platform: wifi_signal
    name: "${upper_devicename} WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "${upper_devicename} Current"
      accuracy_decimals: 1
    voltage:
      name: "${upper_devicename} Voltage"
      accuracy_decimals: 1
    power:
      name: "${upper_devicename} Power"
      accuracy_decimals: 1
switch:
  - platform: gpio
    name: "${upper_devicename} Relay"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON

status_led:
  pin: GPIO13
